http://localhost:3001/api/notes
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "12345",
  "important": true
}
###
http://localhost:3001/api/notes/1
###
http://localhost:3001/api/notes/-1
###
PUT http://localhost:3001/api/notes/3
Content-Type: application/json

{
  "important": false
}